# Generated by Django 3.1.4 on 2020-12-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id_selected_course', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('id_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jadwal.course')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.jadwal')),
            ],
        ),
    ]
