CREATE TABLE PESERTA (
  username VARCHAR(64) NOT NULL,
  password VARCHAR(64) NOT NULL,
  nama VARCHAR(128) NOT NULL,
  finished TINYINT DEFAULT '0',
  PRIMARY KEY(username)
);

CREATE TABLE SOAL (
  id_soal INTEGER UNIQUE NOT NULL,
  soal VARCHAR(1024),
  kunci_jawaban INTEGER NOT NULL,
  PRIMARY KEY(id_soal)
);

CREATE TABLE PILIHAN (
  id_pilihan INTEGER UNIQUE NOT NULL,
  id_soal INTEGER NOT NULL,
  pilihan VARCHAR(1024),
  PRIMARY KEY(id_pilihan)
);

CREATE TABLE DAFTAR_SOAL (
  username VARCHAR(64) NOT NULL,
  id_soal INTEGER NOT NULL,
  urutan INTEGER NOT NULL,
  CONSTRAINT pk_daftar_soal PRIMARY KEY(username, id_soal, urutan)
);
PARTITION TABLE DAFTAR_SOAL ON COLUMN username;

CREATE TABLE JAWABAN (
  username VARCHAR(64) NOT NULL,
  id_soal INTEGER NOT NULL,
  id_pilihan INTEGER NOT NULL,
  CONSTRAINT pk_jawaban PRIMARY KEY(username, id_soal, id_pilihan)
);
PARTITION TABLE JAWABAN ON COLUMN username;
